# Dockerfile
FROM nginx:alpine
# Copy index.html to Nginx default directory
COPY index.html /usr/share/nginx/html/index.html
# Copy local Ace Editor files into the directory
COPY ace /usr/share/nginx/html/ace
