
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    privileged: true
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 15s
      timeout: 30s
      retries: 2

  tester:
    image: python:3.8
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && pytest test_backend.py"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - test_network

networks:
  test_network:
