name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if [ ! -d /home/proyecto/coderService/ ]; then
              echo "Directory /home/proyecto/coderService/ not found. Aborting deployment."
              exit 1
            fi
            cd /home/proyecto/coderService/
            git pull origin main
            docker stop coderService
            docker rm coderService
            docker build -f Dockerfile.fastapi -t coderservice-image . || { echo "Docker build failed"; exit 1; }
            docker run --privileged -d -it -p 5029:8000  -v dind-data:/var/lib/docker --restart unless-stopped --name coderService coderservice-image  || { echo "Docker run failed"; exit 1; }